[book]
authors = ["samiunkonow"]
multilingual = true
src = "src"
title = "AmisynthDocs"


[output.html]
default-theme = "dark"  
preferred-dark-theme = "navy"


[preprocessor.mdbook-discord-components]
after = ["links"]
command = "mdbook-discord-components"
embed-script = false
